version: '3.9'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 8432:5432
    environment:
      POSTGRES_DB: khong
      POSTGRES_USER: khong
      POSTGRES_PASSWORD: khongpass
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: test@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
  local:
    build: 
        context: .
        dockerfile: DevDockerfile
    volumes: 
      - .:/app
    depends_on: 
      - db

    