// Code generated by sqlc. DO NOT EDIT.

package database

import (
	"database/sql"
)

type Message struct {
	Sender      int64
	TicketID    int64
	MessageText string
	MessageID   int64
	ChannelID   int64
}

type Ticket struct {
	ID        int32
	Requester int64
	ChannelID sql.NullInt64
	IsOpen    sql.NullBool
}
